---
- include: centos_packages.yml
  when: ansible_distribution == 'CentOS'

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

# Fail2Ban
- include_tasks: fail2ban.yml
  when: security_fail2ban_enabled | bool

# SSH
- include_tasks: ssh.yml

# Autoupdate
- include_tasks: autoupdate-redhat.yml
  when:
    - ansible_os_family == 'RedHat'
    - security_autoupdate_enabled | bool
